# Generated by Django 2.0 on 2020-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200628_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestgroup',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
