# Generated by Django 2.0 on 2020-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_usertestgroup_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestgroup',
            name='active',
        ),
        migrations.AddField(
            model_name='testgroupconstructor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
