# Generated by Django 2.0 on 2021-04-18 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcersiseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('correctAnswer', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(default='Null', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.CharField(blank=True, max_length=12, null=True, verbose_name='Потраченное время на решение')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Верный ответ')),
                ('given_answer', models.CharField(max_length=200, verbose_name='Данный пользователем ответ')),
                ('answer_is_correct', models.BooleanField(verbose_name='Проверка ответа')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст упражнения')),
                ('exercise_index', models.PositiveIntegerField(default=0, verbose_name='Номер упражнения в тесте')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип примера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип упражнения',
                'verbose_name_plural': 'типы упражнения',
            },
        ),
        migrations.CreateModel(
            name='Replacers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('idNumber', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingApparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfect', models.PositiveIntegerField(verbose_name='Отлично')),
                ('good', models.PositiveIntegerField(verbose_name='Хорошо')),
                ('satisfactory', models.PositiveIntegerField(verbose_name='Удовлетворительно')),
                ('name', models.CharField(max_length=200, verbose_name='Название тренажера')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('exercises_amount', models.PositiveIntegerField(default=0, verbose_name='Количество примеров')),
                ('allotted_time', models.CharField(default='00:00:00', help_text='Формат - "00:00:00"', max_length=9, verbose_name='Время на выполнение')),
                ('exercises_type', models.ForeignKey(blank=True, default=None, help_text='В РАЗРАБОТКЕ', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.ExerciseTypes', verbose_name='Тип(ы) примеров')),
            ],
            options={
                'verbose_name': 'тренажер',
                'verbose_name_plural': 'тренажеры',
            },
        ),
        migrations.CreateModel(
            name='TrainingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(verbose_name='Оценка')),
                ('solved_exercises', models.PositiveIntegerField(default=0, verbose_name='Количество решенных примеров')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Количество верных ответов')),
                ('time_start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время начала тестирования')),
                ('time_spent', models.CharField(blank=True, max_length=10, null=True, verbose_name='Потраченное время на решение')),
                ('apparatus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.TrainingApparatus', verbose_name='Тип тренажера')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'выполненный тест',
                'verbose_name_plural': 'выполненные тесты',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='polls.TrainingTest', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ExerciseTypes', verbose_name='Тип упражнения'),
        ),
    ]
