# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(max_length=200)),
                ('sll', models.CharField(max_length=200)),
                ('summ', models.CharField(max_length=200)),
                ('znak', models.CharField(max_length=200)),
            ],
        ),
    ]
