# Generated by Django 2.0 on 2020-01-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('time_spent', models.TimeField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('given_answer', models.CharField(max_length=200)),
                ('answer_is_correct', models.BooleanField()),
                ('text', models.TextField(max_length=1000)),
            ],
        ),

    ]
