# Generated by Django 2.0 on 2021-06-17 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Составьте математическое выражение, используя буквенные обозначения прикрепленных переменных.', max_length=100, verbose_name='текст шаблона')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблоны',
            },
        ),
        migrations.CreateModel(
            name='ExerciseVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='буквенное обозначение')),
                ('var_type', models.CharField(choices=[('int', 'Целое'), ('float', 'Дробное')], default='int', max_length=5)),
                ('interval_min', models.DecimalField(decimal_places=2, default=0, help_text='Интервал для генерации переменной.', max_digits=10, verbose_name='начало интервала')),
                ('interval_max', models.DecimalField(decimal_places=2, default=0, help_text='Интервал для генерации переменной.', max_digits=10, verbose_name='конец интервала')),
            ],
            options={
                'verbose_name': 'переменная',
                'verbose_name_plural': 'переменные',
            },
        ),
        migrations.AlterField(
            model_name='trainingapparatus',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='exercisetypes',
            name='templates',
            field=models.ManyToManyField(related_name='types', to='polls.ExerciseTemplate', verbose_name='шаблон(ы)'),
        ),
    ]
