# Generated by Django 2.0 on 2020-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200102_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correct_answers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
