# Generated by Django 2.0 on 2020-02-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200208_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtest',
            name='time_spent',
        ),
    ]
