# Generated by Django 2.0 on 2020-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_trainingtest_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtest',
            name='time_spent',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
