# Generated by Django 2.0 on 2020-04-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_trainingtest_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'упражнение', 'verbose_name_plural': 'упражнения'},
        ),
        migrations.AlterModelOptions(
            name='exercisetypes',
            options={'verbose_name': 'тип упражнения', 'verbose_name_plural': 'типы упражнения'},
        ),
        migrations.AlterModelOptions(
            name='trainingapparatus',
            options={'verbose_name': 'тренажер', 'verbose_name_plural': 'тренажеры'},
        ),
        migrations.AlterModelOptions(
            name='trainingtest',
            options={'verbose_name': 'выполненный тест', 'verbose_name_plural': 'выполненные тесты'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='test_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TrainingTest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer_is_correct',
            field=models.BooleanField(verbose_name='Проверка ответа'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(max_length=200, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер упражнения в тесте'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='given_answer',
            field=models.CharField(max_length=200, verbose_name='Данный пользователем ответ'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст упражнения'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_spent',
            field=models.TimeField(blank=True, null=True, verbose_name='Потраченное время на решение'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ExerciseTypes', verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='trainingapparatus',
            name='allotted_time',
            field=models.CharField(default='00:00:00', help_text='Формат - "00:00:00"', max_length=9, verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='trainingapparatus',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainingapparatus',
            name='exercises_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество примеров'),
        ),
        migrations.AlterField(
            model_name='trainingapparatus',
            name='exercises_type',
            field=models.ForeignKey(blank=True, default=None, help_text='В РАЗРАБОТКЕ', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.ExerciseTypes', verbose_name='Тип(ы) примеров'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='apparatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.TrainingApparatus', verbose_name='Тип тренажера'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество верных ответов'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='grade',
            field=models.PositiveIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='solved_exercises',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество решенных примеров'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='time_spent',
            field=models.TimeField(blank=True, null=True, verbose_name='Потраченное время на решение'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='time_start',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала тестирования'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
