# Generated by Django 2.0 on 2020-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200404_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtest',
            name='time_spent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Потраченное время на решение'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время начала тестирования'),
        ),
    ]
