# Generated by Django 2.0 on 2020-04-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200425_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time_spent',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Потраченное время на решение'),
        ),
    ]
